name: Build nightly

on:
  # Run daily, on dispatch and after new pushes to main
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
  workflow_run:
    workflows: [Build and test]
    types:
      - completed
env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build nightly
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Get nightly Rust toolchain
        uses: dtolnay/rust-toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true
          targets: thumbv7em-none-eabihf
      - name: Use Rust Cache
        if: ${{ runner.os == 'Linux' }}
        uses: Swatinem/rust-cache@v2.0.1
      - name: Clone flipperzero-firmware
        run: git clone --recursive https://github.com/flipperdevices/flipperzero-firmware
      - name: Build flipperzero-firmware
        run: cd flipperzero-firmware && ./fbt
      - name: Install libudev-dev
        run: sudo apt install libudev-dev
      - name: Generate bindings
        run: cd tools && cargo run --bin generate-bindings ../flipperzero-firmware/build/f7-firmware-D/sdk-headers && cp bindings.rs ../crates/sys/src
      - name: Run cargo build
        run: cd crates && cargo build --release
      - name: Commit Files
        run: |
          git config --local user.email "nightly-bot@spam4.me"
          git config --local user.name "Nightly Bot"
          git add crates/sys/src/bindings.rs
          git commit -m "Update bindings"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: nightly
